### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by DreamyKiley** [DreamyKiley/PySnap#1]
- [ ] Fix double pressing
- [ ] Fix Linux implementation 
<sub>I'm a windows beby so I might struggle with this, but did the best I could, it *was* working and not it doesn't lul</sub>
- [ ] Make a changeable hotkey
