### ISSUE TITLE
To-Do / Double Pressing Issue

### ISSUE THREAD

**Issue by DreamyKiley** [DreamyKiley/PySnap#1]
## To-Do List

- [x] Initial post
- [ ] Fix Double Pressing 
_(This generally won't affect you in game, I have yet to have it bother me other than typing, but I just use my mic so not high on my list of priorities)_
- [ ] Make the hotkey able to be changed from F5 easily
- [ ] Add the ability to do W and S as well one day
